/**
 * Mapping of PascalCase keys to proper country names
 * This provides the canonical display names for all countries
 */
export const CountryNames: Record<string, string> = {
  Afghanistan: "Afghanistan",
  AlandIslands: "Åland Islands",
  Albania: "Albania",
  Algeria: "Algeria",
  AmericanSamoa: "American Samoa",
  Andorra: "Andorra",
  Angola: "Angola",
  Anguilla: "Anguilla",
  AntiguaandBarbuda: "Antigua and Barbuda",
  Argentina: "Argentina",
  Armenia: "Armenia",
  Aruba: "Aruba",
  Australia: "Australia",
  Austria: "Austria",
  Azerbaijan: "Azerbaijan",
  Bahamas: "Bahamas",
  Bahrain: "Bahrain",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Belarus: "Belarus",
  Belgium: "Belgium",
  Belize: "Belize",
  Benin: "Benin",
  Bermuda: "Bermuda",
  Bhutan: "Bhutan",
  Bolivia: "Bolivia",
  BonaireSintEustatiusandSaba: "Bonaire, Sint Eustatius and Saba",
  BosniaandHerzegovina: "Bosnia and Herzegovina",
  Botswana: "Botswana",
  Brazil: "Brazil",
  BritishIndianOceanTerritory: "British Indian Ocean Territory",
  BritishVirginIslands: "British Virgin Islands",
  Brunei: "Brunei",
  Bulgaria: "Bulgaria",
  BurkinaFaso: "Burkina Faso",
  Burundi: "Burundi",
  CaboVerde: "Cabo Verde",
  Cambodia: "Cambodia",
  Cameroon: "Cameroon",
  Canada: "Canada",
  CaymanIslands: "Cayman Islands",
  CentralAfricanRepublic: "Central African Republic",
  Chad: "Chad",
  Chile: "Chile",
  China: "China",
  ChristmasIsland: "Christmas Island",
  Cocos_Keeling_Islands: "Cocos (Keeling) Islands",
  Colombia: "Colombia",
  Comoros: "Comoros",
  Congo: "Congo",
  Congo_DRC: "Congo (DRC)",
  CookIslands: "Cook Islands",
  CostaRica: "Costa Rica",
  CotedIvoire: "Côte d'Ivoire",
  Croatia: "Croatia",
  Cuba: "Cuba",
  Curacao: "Curaçao",
  Cyprus: "Cyprus",
  Czechia: "Czechia",
  Denmark: "Denmark",
  Djibouti: "Djibouti",
  Dominica: "Dominica",
  DominicanRepublic: "Dominican Republic",
  Ecuador: "Ecuador",
  Egypt: "Egypt",
  ElSalvador: "El Salvador",
  EquatorialGuinea: "Equatorial Guinea",
  Eritrea: "Eritrea",
  Estonia: "Estonia",
  Eswatini: "Eswatini",
  Ethiopia: "Ethiopia",
  FalklandIslands: "Falkland Islands",
  FaroeIslands: "Faroe Islands",
  Fiji: "Fiji",
  Finland: "Finland",
  France: "France",
  FrenchGuiana: "French Guiana",
  FrenchPolynesia: "French Polynesia",
  Gabon: "Gabon",
  Gambia: "Gambia",
  Georgia: "Georgia",
  Germany: "Germany",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  Greece: "Greece",
  Greenland: "Greenland",
  Grenada: "Grenada",
  Guadeloupe: "Guadeloupe",
  Guam: "Guam",
  Guatemala: "Guatemala",
  Guernsey: "Guernsey",
  Guinea: "Guinea",
  GuineaBissau: "Guinea-Bissau",
  Guyana: "Guyana",
  Haiti: "Haiti",
  Honduras: "Honduras",
  HongKongSAR: "Hong Kong SAR",
  Hungary: "Hungary",
  Iceland: "Iceland",
  India: "India",
  Indonesia: "Indonesia",
  Iran: "Iran",
  Iraq: "Iraq",
  Ireland: "Ireland",
  IsleofMan: "Isle of Man",
  Israel: "Israel",
  Italy: "Italy",
  Jamaica: "Jamaica",
  Japan: "Japan",
  Jersey: "Jersey",
  Jordan: "Jordan",
  Kazakhstan: "Kazakhstan",
  Kenya: "Kenya",
  Kiribati: "Kiribati",
  Korea: "Korea",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Kyrgyzstan",
  Laos: "Laos",
  Latvia: "Latvia",
  Lebanon: "Lebanon",
  Lesotho: "Lesotho",
  Liberia: "Liberia",
  Libya: "Libya",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lithuania",
  Luxembourg: "Luxembourg",
  MacaoSAR: "Macao SAR",
  Madagascar: "Madagascar",
  Malawi: "Malawi",
  Malaysia: "Malaysia",
  Maldives: "Maldives",
  Mali: "Mali",
  Malta: "Malta",
  MarshallIslands: "Marshall Islands",
  Martinique: "Martinique",
  Mauritania: "Mauritania",
  Mauritius: "Mauritius",
  Mayotte: "Mayotte",
  Mexico: "Mexico",
  Micronesia: "Micronesia",
  Moldova: "Moldova",
  Monaco: "Monaco",
  Mongolia: "Mongolia",
  Montenegro: "Montenegro",
  Montserrat: "Montserrat",
  Morocco: "Morocco",
  Mozambique: "Mozambique",
  Myanmar: "Myanmar",
  Namibia: "Namibia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Netherlands",
  NewCaledonia: "New Caledonia",
  NewZealand: "New Zealand",
  Nicaragua: "Nicaragua",
  Niger: "Niger",
  Nigeria: "Nigeria",
  Niue: "Niue",
  NorfolkIsland: "Norfolk Island",
  NorthKorea: "North Korea",
  NorthMacedonia: "North Macedonia",
  NorthernMarianaIslands: "Northern Mariana Islands",
  Norway: "Norway",
  Oman: "Oman",
  Pakistan: "Pakistan",
  Palau: "Palau",
  PalestinianAuthority: "Palestinian Authority",
  Panama: "Panama",
  PapuaNewGuinea: "Papua New Guinea",
  Paraguay: "Paraguay",
  Peru: "Peru",
  Philippines: "Philippines",
  PitcairnIslands: "Pitcairn Islands",
  Poland: "Poland",
  Portugal: "Portugal",
  PuertoRico: "Puerto Rico",
  Qatar: "Qatar",
  Reunion: "Réunion",
  Romania: "Romania",
  Russia: "Russia",
  Rwanda: "Rwanda",
  Samoa: "Samoa",
  SanMarino: "San Marino",
  SaoTomeandPrincipe: "São Tomé and Príncipe",
  SaudiArabia: "Saudi Arabia",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Seychelles: "Seychelles",
  SierraLeone: "Sierra Leone",
  Singapore: "Singapore",
  SintMaarten: "Sint Maarten",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  SolomonIslands: "Solomon Islands",
  Somalia: "Somalia",
  SouthAfrica: "South Africa",
  SouthSudan: "South Sudan",
  Spain: "Spain",
  SriLanka: "Sri Lanka",
  StHelenaAscensionTristandaCunha: "St. Helena, Ascension, Tristan da Cunha",
  StBarthelemy: "St. Barthélemy",
  StKittsandNevis: "St. Kitts and Nevis",
  StLucia: "St. Lucia",
  StMartin: "St. Martin",
  StPierreandMiquelon: "St. Pierre and Miquelon",
  StVincentandtheGrenadines: "St. Vincent and the Grenadines",
  Sudan: "Sudan",
  Suriname: "Suriname",
  SvalbardandJanMayen: "Svalbard and Jan Mayen",
  Sweden: "Sweden",
  Switzerland: "Switzerland",
  Syria: "Syria",
  Taiwan: "Taiwan",
  Tajikistan: "Tajikistan",
  Tanzania: "Tanzania",
  Thailand: "Thailand",
  TimorLeste: "Timor-Leste",
  Togo: "Togo",
  Tokelau: "Tokelau",
  Tonga: "Tonga",
  TrinidadandTobago: "Trinidad and Tobago",
  Tunisia: "Tunisia",
  Turkey: "Turkey",
  Turkmenistan: "Turkmenistan",
  TurksandCaicosIslands: "Turks and Caicos Islands",
  Tuvalu: "Tuvalu",
  USOutlyingIslands: "U.S. Outlying Islands",
  USVirginIslands: "U.S. Virgin Islands",
  Uganda: "Uganda",
  Ukraine: "Ukraine",
  UnitedArabEmirates: "United Arab Emirates",
  UnitedKingdom: "United Kingdom",
  UnitedStates: "United States",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistan",
  Vanuatu: "Vanuatu",
  VaticanCity: "Vatican City",
  Venezuela: "Venezuela",
  Vietnam: "Vietnam",
  WallisandFutuna: "Wallis and Futuna",
  Yemen: "Yemen",
  Zambia: "Zambia",
  Zimbabwe: "Zimbabwe"
};

